/**
 * bt-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface AccessToken {
    id: string;

    /**
     * time to live in seconds (2 weeks by default)
     */
    ttl?: number;

    /**
     * Array of scopes granted to this access token.
     */
    scopes?: Array<string>;

    created?: Date;

    userId?: number;

}
